## SQL para Estoque Global
Vá no seu painel do Supabase, acesse **SQL Editor**, e rode o seguinte código para criar a tabela de estoque e remover a "gambiarra" do `templates_espetaculos`:

```sql
CREATE TABLE public.estoque_global (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itens JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Migra os dados existentes do template ESTOQUE_GLOBAL (se houver)
INSERT INTO public.estoque_global (itens)
SELECT COALESCE(assets_midia->'malas_padrao', '[]'::jsonb)
FROM public.templates_espetaculos
WHERE nome_espetaculo = 'ESTOQUE_GLOBAL';

-- Caso esteja vazio, insere uma linha em branco
INSERT INTO public.estoque_global (itens)
SELECT '[]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.estoque_global);

-- Remove a gambiarra do template para parar de aparecer nos dropdowns
DELETE FROM public.templates_espetaculos WHERE nome_espetaculo = 'ESTOQUE_GLOBAL';

-- RLS policies
ALTER TABLE public.estoque_global ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for authenticated users" ON public.estoque_global FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable update for authenticated users" ON public.estoque_global FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.estoque_global FOR INSERT TO authenticated WITH CHECK (true);
```
