/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyPhoneRouteImport } from './routes/verify-phone'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurneSlugRouteImport } from './routes/turne.$slug'
import { Route as TurneCompletaSlugRouteImport } from './routes/turne-completa.$slug'
import { Route as RbSlugRouteImport } from './routes/rb.$slug'
import { Route as MotoristaPrintSlugRouteImport } from './routes/motorista-print.$slug'
import { Route as AuthenticatedPublicoRouteImport } from './routes/_authenticated/publico'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinhasEscalasRouteImport } from './routes/_authenticated/minhas-escalas'
import { Route as AuthenticatedMeusPagamentosRouteImport } from './routes/_authenticated/meus-pagamentos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedEscalasRouteImport } from './routes/_authenticated/escalas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDadosPessoaisRouteImport } from './routes/_authenticated/dados-pessoais'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedSomIndexRouteImport } from './routes/_authenticated/som.index'
import { Route as AuthenticatedIluminacaoIndexRouteImport } from './routes/_authenticated/iluminacao.index'
import { Route as AuthenticatedVersaoMotoristaSlugRouteImport } from './routes/_authenticated/versao-motorista.$slug'
import { Route as AuthenticatedTourNewRouteImport } from './routes/_authenticated/tour.new'
import { Route as AuthenticatedTourIdRouteImport } from './routes/_authenticated/tour.$id'
import { Route as AuthenticatedSomEvento_idRouteImport } from './routes/_authenticated/som.$evento_id'
import { Route as AuthenticatedRoadbookNewRouteImport } from './routes/_authenticated/roadbook.new'
import { Route as AuthenticatedRoadbookIdRouteImport } from './routes/_authenticated/roadbook.$id'
import { Route as AuthenticatedPrintSlugRouteImport } from './routes/_authenticated/print.$slug'
import { Route as AuthenticatedIluminacaoEvento_idRouteImport } from './routes/_authenticated/iluminacao.$evento_id'

const VerifyPhoneRoute = VerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneSlugRoute = TurneSlugRouteImport.update({
  id: '/turne/$slug',
  path: '/turne/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneCompletaSlugRoute = TurneCompletaSlugRouteImport.update({
  id: '/turne-completa/$slug',
  path: '/turne-completa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RbSlugRoute = RbSlugRouteImport.update({
  id: '/rb/$slug',
  path: '/rb/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaPrintSlugRoute = MotoristaPrintSlugRouteImport.update({
  id: '/motorista-print/$slug',
  path: '/motorista-print/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPublicoRoute = AuthenticatedPublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasEscalasRoute =
  AuthenticatedMinhasEscalasRouteImport.update({
    id: '/minhas-escalas',
    path: '/minhas-escalas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusPagamentosRoute =
  AuthenticatedMeusPagamentosRouteImport.update({
    id: '/meus-pagamentos',
    path: '/meus-pagamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalasRoute = AuthenticatedEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDadosPessoaisRoute =
  AuthenticatedDadosPessoaisRouteImport.update({
    id: '/dados-pessoais',
    path: '/dados-pessoais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSomIndexRoute = AuthenticatedSomIndexRouteImport.update({
  id: '/som/',
  path: '/som/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIluminacaoIndexRoute =
  AuthenticatedIluminacaoIndexRouteImport.update({
    id: '/iluminacao/',
    path: '/iluminacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVersaoMotoristaSlugRoute =
  AuthenticatedVersaoMotoristaSlugRouteImport.update({
    id: '/versao-motorista/$slug',
    path: '/versao-motorista/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourNewRoute = AuthenticatedTourNewRouteImport.update({
  id: '/tour/new',
  path: '/tour/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTourIdRoute = AuthenticatedTourIdRouteImport.update({
  id: '/tour/$id',
  path: '/tour/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSomEvento_idRoute =
  AuthenticatedSomEvento_idRouteImport.update({
    id: '/som/$evento_id',
    path: '/som/$evento_id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadbookNewRoute =
  AuthenticatedRoadbookNewRouteImport.update({
    id: '/roadbook/new',
    path: '/roadbook/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadbookIdRoute = AuthenticatedRoadbookIdRouteImport.update({
  id: '/roadbook/$id',
  path: '/roadbook/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintSlugRoute = AuthenticatedPrintSlugRouteImport.update({
  id: '/print/$slug',
  path: '/print/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIluminacaoEvento_idRoute =
  AuthenticatedIluminacaoEvento_idRouteImport.update({
    id: '/iluminacao/$evento_id',
    path: '/iluminacao/$evento_id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/dados-pessoais': typeof AuthenticatedDadosPessoaisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/meus-pagamentos': typeof AuthenticatedMeusPagamentosRoute
  '/minhas-escalas': typeof AuthenticatedMinhasEscalasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publico': typeof AuthenticatedPublicoRoute
  '/motorista-print/$slug': typeof MotoristaPrintSlugRoute
  '/rb/$slug': typeof RbSlugRoute
  '/turne-completa/$slug': typeof TurneCompletaSlugRoute
  '/turne/$slug': typeof TurneSlugRoute
  '/iluminacao/$evento_id': typeof AuthenticatedIluminacaoEvento_idRoute
  '/print/$slug': typeof AuthenticatedPrintSlugRoute
  '/roadbook/$id': typeof AuthenticatedRoadbookIdRoute
  '/roadbook/new': typeof AuthenticatedRoadbookNewRoute
  '/som/$evento_id': typeof AuthenticatedSomEvento_idRoute
  '/tour/$id': typeof AuthenticatedTourIdRoute
  '/tour/new': typeof AuthenticatedTourNewRoute
  '/versao-motorista/$slug': typeof AuthenticatedVersaoMotoristaSlugRoute
  '/iluminacao/': typeof AuthenticatedIluminacaoIndexRoute
  '/som/': typeof AuthenticatedSomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/dados-pessoais': typeof AuthenticatedDadosPessoaisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escalas': typeof AuthenticatedEscalasRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/meus-pagamentos': typeof AuthenticatedMeusPagamentosRoute
  '/minhas-escalas': typeof AuthenticatedMinhasEscalasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/publico': typeof AuthenticatedPublicoRoute
  '/motorista-print/$slug': typeof MotoristaPrintSlugRoute
  '/rb/$slug': typeof RbSlugRoute
  '/turne-completa/$slug': typeof TurneCompletaSlugRoute
  '/turne/$slug': typeof TurneSlugRoute
  '/iluminacao/$evento_id': typeof AuthenticatedIluminacaoEvento_idRoute
  '/print/$slug': typeof AuthenticatedPrintSlugRoute
  '/roadbook/$id': typeof AuthenticatedRoadbookIdRoute
  '/roadbook/new': typeof AuthenticatedRoadbookNewRoute
  '/som/$evento_id': typeof AuthenticatedSomEvento_idRoute
  '/tour/$id': typeof AuthenticatedTourIdRoute
  '/tour/new': typeof AuthenticatedTourNewRoute
  '/versao-motorista/$slug': typeof AuthenticatedVersaoMotoristaSlugRoute
  '/iluminacao': typeof AuthenticatedIluminacaoIndexRoute
  '/som': typeof AuthenticatedSomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/verify-phone': typeof VerifyPhoneRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/dados-pessoais': typeof AuthenticatedDadosPessoaisRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/escalas': typeof AuthenticatedEscalasRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/meus-pagamentos': typeof AuthenticatedMeusPagamentosRoute
  '/_authenticated/minhas-escalas': typeof AuthenticatedMinhasEscalasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/publico': typeof AuthenticatedPublicoRoute
  '/motorista-print/$slug': typeof MotoristaPrintSlugRoute
  '/rb/$slug': typeof RbSlugRoute
  '/turne-completa/$slug': typeof TurneCompletaSlugRoute
  '/turne/$slug': typeof TurneSlugRoute
  '/_authenticated/iluminacao/$evento_id': typeof AuthenticatedIluminacaoEvento_idRoute
  '/_authenticated/print/$slug': typeof AuthenticatedPrintSlugRoute
  '/_authenticated/roadbook/$id': typeof AuthenticatedRoadbookIdRoute
  '/_authenticated/roadbook/new': typeof AuthenticatedRoadbookNewRoute
  '/_authenticated/som/$evento_id': typeof AuthenticatedSomEvento_idRoute
  '/_authenticated/tour/$id': typeof AuthenticatedTourIdRoute
  '/_authenticated/tour/new': typeof AuthenticatedTourNewRoute
  '/_authenticated/versao-motorista/$slug': typeof AuthenticatedVersaoMotoristaSlugRoute
  '/_authenticated/iluminacao/': typeof AuthenticatedIluminacaoIndexRoute
  '/_authenticated/som/': typeof AuthenticatedSomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/verify-phone'
    | '/cadastros'
    | '/configuracoes'
    | '/contatos'
    | '/dados-pessoais'
    | '/dashboard'
    | '/escalas'
    | '/eventos'
    | '/financeiro'
    | '/meus-pagamentos'
    | '/minhas-escalas'
    | '/perfil'
    | '/publico'
    | '/motorista-print/$slug'
    | '/rb/$slug'
    | '/turne-completa/$slug'
    | '/turne/$slug'
    | '/iluminacao/$evento_id'
    | '/print/$slug'
    | '/roadbook/$id'
    | '/roadbook/new'
    | '/som/$evento_id'
    | '/tour/$id'
    | '/tour/new'
    | '/versao-motorista/$slug'
    | '/iluminacao/'
    | '/som/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/verify-phone'
    | '/cadastros'
    | '/configuracoes'
    | '/contatos'
    | '/dados-pessoais'
    | '/dashboard'
    | '/escalas'
    | '/eventos'
    | '/financeiro'
    | '/meus-pagamentos'
    | '/minhas-escalas'
    | '/perfil'
    | '/publico'
    | '/motorista-print/$slug'
    | '/rb/$slug'
    | '/turne-completa/$slug'
    | '/turne/$slug'
    | '/iluminacao/$evento_id'
    | '/print/$slug'
    | '/roadbook/$id'
    | '/roadbook/new'
    | '/som/$evento_id'
    | '/tour/$id'
    | '/tour/new'
    | '/versao-motorista/$slug'
    | '/iluminacao'
    | '/som'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/verify-phone'
    | '/_authenticated/cadastros'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/dados-pessoais'
    | '/_authenticated/dashboard'
    | '/_authenticated/escalas'
    | '/_authenticated/eventos'
    | '/_authenticated/financeiro'
    | '/_authenticated/meus-pagamentos'
    | '/_authenticated/minhas-escalas'
    | '/_authenticated/perfil'
    | '/_authenticated/publico'
    | '/motorista-print/$slug'
    | '/rb/$slug'
    | '/turne-completa/$slug'
    | '/turne/$slug'
    | '/_authenticated/iluminacao/$evento_id'
    | '/_authenticated/print/$slug'
    | '/_authenticated/roadbook/$id'
    | '/_authenticated/roadbook/new'
    | '/_authenticated/som/$evento_id'
    | '/_authenticated/tour/$id'
    | '/_authenticated/tour/new'
    | '/_authenticated/versao-motorista/$slug'
    | '/_authenticated/iluminacao/'
    | '/_authenticated/som/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifyPhoneRoute: typeof VerifyPhoneRoute
  MotoristaPrintSlugRoute: typeof MotoristaPrintSlugRoute
  RbSlugRoute: typeof RbSlugRoute
  TurneCompletaSlugRoute: typeof TurneCompletaSlugRoute
  TurneSlugRoute: typeof TurneSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-phone': {
      id: '/verify-phone'
      path: '/verify-phone'
      fullPath: '/verify-phone'
      preLoaderRoute: typeof VerifyPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turne/$slug': {
      id: '/turne/$slug'
      path: '/turne/$slug'
      fullPath: '/turne/$slug'
      preLoaderRoute: typeof TurneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turne-completa/$slug': {
      id: '/turne-completa/$slug'
      path: '/turne-completa/$slug'
      fullPath: '/turne-completa/$slug'
      preLoaderRoute: typeof TurneCompletaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rb/$slug': {
      id: '/rb/$slug'
      path: '/rb/$slug'
      fullPath: '/rb/$slug'
      preLoaderRoute: typeof RbSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista-print/$slug': {
      id: '/motorista-print/$slug'
      path: '/motorista-print/$slug'
      fullPath: '/motorista-print/$slug'
      preLoaderRoute: typeof MotoristaPrintSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/publico': {
      id: '/_authenticated/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof AuthenticatedPublicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-escalas': {
      id: '/_authenticated/minhas-escalas'
      path: '/minhas-escalas'
      fullPath: '/minhas-escalas'
      preLoaderRoute: typeof AuthenticatedMinhasEscalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-pagamentos': {
      id: '/_authenticated/meus-pagamentos'
      path: '/meus-pagamentos'
      fullPath: '/meus-pagamentos'
      preLoaderRoute: typeof AuthenticatedMeusPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escalas': {
      id: '/_authenticated/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof AuthenticatedEscalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dados-pessoais': {
      id: '/_authenticated/dados-pessoais'
      path: '/dados-pessoais'
      fullPath: '/dados-pessoais'
      preLoaderRoute: typeof AuthenticatedDadosPessoaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/som/': {
      id: '/_authenticated/som/'
      path: '/som'
      fullPath: '/som/'
      preLoaderRoute: typeof AuthenticatedSomIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iluminacao/': {
      id: '/_authenticated/iluminacao/'
      path: '/iluminacao'
      fullPath: '/iluminacao/'
      preLoaderRoute: typeof AuthenticatedIluminacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versao-motorista/$slug': {
      id: '/_authenticated/versao-motorista/$slug'
      path: '/versao-motorista/$slug'
      fullPath: '/versao-motorista/$slug'
      preLoaderRoute: typeof AuthenticatedVersaoMotoristaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour/new': {
      id: '/_authenticated/tour/new'
      path: '/tour/new'
      fullPath: '/tour/new'
      preLoaderRoute: typeof AuthenticatedTourNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour/$id': {
      id: '/_authenticated/tour/$id'
      path: '/tour/$id'
      fullPath: '/tour/$id'
      preLoaderRoute: typeof AuthenticatedTourIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/som/$evento_id': {
      id: '/_authenticated/som/$evento_id'
      path: '/som/$evento_id'
      fullPath: '/som/$evento_id'
      preLoaderRoute: typeof AuthenticatedSomEvento_idRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadbook/new': {
      id: '/_authenticated/roadbook/new'
      path: '/roadbook/new'
      fullPath: '/roadbook/new'
      preLoaderRoute: typeof AuthenticatedRoadbookNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadbook/$id': {
      id: '/_authenticated/roadbook/$id'
      path: '/roadbook/$id'
      fullPath: '/roadbook/$id'
      preLoaderRoute: typeof AuthenticatedRoadbookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/$slug': {
      id: '/_authenticated/print/$slug'
      path: '/print/$slug'
      fullPath: '/print/$slug'
      preLoaderRoute: typeof AuthenticatedPrintSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iluminacao/$evento_id': {
      id: '/_authenticated/iluminacao/$evento_id'
      path: '/iluminacao/$evento_id'
      fullPath: '/iluminacao/$evento_id'
      preLoaderRoute: typeof AuthenticatedIluminacaoEvento_idRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedDadosPessoaisRoute: typeof AuthenticatedDadosPessoaisRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEscalasRoute: typeof AuthenticatedEscalasRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMeusPagamentosRoute: typeof AuthenticatedMeusPagamentosRoute
  AuthenticatedMinhasEscalasRoute: typeof AuthenticatedMinhasEscalasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPublicoRoute: typeof AuthenticatedPublicoRoute
  AuthenticatedIluminacaoEvento_idRoute: typeof AuthenticatedIluminacaoEvento_idRoute
  AuthenticatedPrintSlugRoute: typeof AuthenticatedPrintSlugRoute
  AuthenticatedRoadbookIdRoute: typeof AuthenticatedRoadbookIdRoute
  AuthenticatedRoadbookNewRoute: typeof AuthenticatedRoadbookNewRoute
  AuthenticatedSomEvento_idRoute: typeof AuthenticatedSomEvento_idRoute
  AuthenticatedTourIdRoute: typeof AuthenticatedTourIdRoute
  AuthenticatedTourNewRoute: typeof AuthenticatedTourNewRoute
  AuthenticatedVersaoMotoristaSlugRoute: typeof AuthenticatedVersaoMotoristaSlugRoute
  AuthenticatedIluminacaoIndexRoute: typeof AuthenticatedIluminacaoIndexRoute
  AuthenticatedSomIndexRoute: typeof AuthenticatedSomIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedDadosPessoaisRoute: AuthenticatedDadosPessoaisRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEscalasRoute: AuthenticatedEscalasRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMeusPagamentosRoute: AuthenticatedMeusPagamentosRoute,
  AuthenticatedMinhasEscalasRoute: AuthenticatedMinhasEscalasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPublicoRoute: AuthenticatedPublicoRoute,
  AuthenticatedIluminacaoEvento_idRoute: AuthenticatedIluminacaoEvento_idRoute,
  AuthenticatedPrintSlugRoute: AuthenticatedPrintSlugRoute,
  AuthenticatedRoadbookIdRoute: AuthenticatedRoadbookIdRoute,
  AuthenticatedRoadbookNewRoute: AuthenticatedRoadbookNewRoute,
  AuthenticatedSomEvento_idRoute: AuthenticatedSomEvento_idRoute,
  AuthenticatedTourIdRoute: AuthenticatedTourIdRoute,
  AuthenticatedTourNewRoute: AuthenticatedTourNewRoute,
  AuthenticatedVersaoMotoristaSlugRoute: AuthenticatedVersaoMotoristaSlugRoute,
  AuthenticatedIluminacaoIndexRoute: AuthenticatedIluminacaoIndexRoute,
  AuthenticatedSomIndexRoute: AuthenticatedSomIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifyPhoneRoute: VerifyPhoneRoute,
  MotoristaPrintSlugRoute: MotoristaPrintSlugRoute,
  RbSlugRoute: RbSlugRoute,
  TurneCompletaSlugRoute: TurneCompletaSlugRoute,
  TurneSlugRoute: TurneSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
