/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurneSlugRouteImport } from './routes/turne.$slug'
import { Route as TurneCompletaSlugRouteImport } from './routes/turne-completa.$slug'
import { Route as RbSlugRouteImport } from './routes/rb.$slug'
import { Route as MotoristaPrintSlugRouteImport } from './routes/motorista-print.$slug'
import { Route as AuthenticatedSomRouteImport } from './routes/_authenticated/som'
import { Route as AuthenticatedPublicoRouteImport } from './routes/_authenticated/publico'
import { Route as AuthenticatedIluminacaoRouteImport } from './routes/_authenticated/iluminacao'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedVersaoMotoristaSlugRouteImport } from './routes/_authenticated/versao-motorista.$slug'
import { Route as AuthenticatedTourNewRouteImport } from './routes/_authenticated/tour.new'
import { Route as AuthenticatedTourIdRouteImport } from './routes/_authenticated/tour.$id'
import { Route as AuthenticatedRoadbookNewRouteImport } from './routes/_authenticated/roadbook.new'
import { Route as AuthenticatedRoadbookIdRouteImport } from './routes/_authenticated/roadbook.$id'
import { Route as AuthenticatedPrintSlugRouteImport } from './routes/_authenticated/print.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneSlugRoute = TurneSlugRouteImport.update({
  id: '/turne/$slug',
  path: '/turne/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneCompletaSlugRoute = TurneCompletaSlugRouteImport.update({
  id: '/turne-completa/$slug',
  path: '/turne-completa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RbSlugRoute = RbSlugRouteImport.update({
  id: '/rb/$slug',
  path: '/rb/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaPrintSlugRoute = MotoristaPrintSlugRouteImport.update({
  id: '/motorista-print/$slug',
  path: '/motorista-print/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSomRoute = AuthenticatedSomRouteImport.update({
  id: '/som',
  path: '/som',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublicoRoute = AuthenticatedPublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIluminacaoRoute = AuthenticatedIluminacaoRouteImport.update({
  id: '/iluminacao',
  path: '/iluminacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVersaoMotoristaSlugRoute =
  AuthenticatedVersaoMotoristaSlugRouteImport.update({
    id: '/versao-motorista/$slug',
    path: '/versao-motorista/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTourNewRoute = AuthenticatedTourNewRouteImport.update({
  id: '/tour/new',
  path: '/tour/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTourIdRoute = AuthenticatedTourIdRouteImport.update({
  id: '/tour/$id',
  path: '/tour/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadbookNewRoute =
  AuthenticatedRoadbookNewRouteImport.update({
    id: '/roadbook/new',
    path: '/roadbook/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoadbookIdRoute = AuthenticatedRoadbookIdRouteImport.update({
  id: '/roadbook/$id',
  path: '/roadbook/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintSlugRoute = AuthenticatedPrintSlugRouteImport.update({
  id: '/print/$slug',
  path: '/print/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/iluminacao': typeof AuthenticatedIluminacaoRoute
  '/publico': typeof AuthenticatedPublicoRoute
  '/som': typeof AuthenticatedSomRoute
  '/motorista-print/$slug': typeof MotoristaPrintSlugRoute
  '/rb/$slug': typeof RbSlugRoute
  '/turne-completa/$slug': typeof TurneCompletaSlugRoute
  '/turne/$slug': typeof TurneSlugRoute
  '/print/$slug': typeof AuthenticatedPrintSlugRoute
  '/roadbook/$id': typeof AuthenticatedRoadbookIdRoute
  '/roadbook/new': typeof AuthenticatedRoadbookNewRoute
  '/tour/$id': typeof AuthenticatedTourIdRoute
  '/tour/new': typeof AuthenticatedTourNewRoute
  '/versao-motorista/$slug': typeof AuthenticatedVersaoMotoristaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/iluminacao': typeof AuthenticatedIluminacaoRoute
  '/publico': typeof AuthenticatedPublicoRoute
  '/som': typeof AuthenticatedSomRoute
  '/motorista-print/$slug': typeof MotoristaPrintSlugRoute
  '/rb/$slug': typeof RbSlugRoute
  '/turne-completa/$slug': typeof TurneCompletaSlugRoute
  '/turne/$slug': typeof TurneSlugRoute
  '/print/$slug': typeof AuthenticatedPrintSlugRoute
  '/roadbook/$id': typeof AuthenticatedRoadbookIdRoute
  '/roadbook/new': typeof AuthenticatedRoadbookNewRoute
  '/tour/$id': typeof AuthenticatedTourIdRoute
  '/tour/new': typeof AuthenticatedTourNewRoute
  '/versao-motorista/$slug': typeof AuthenticatedVersaoMotoristaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/iluminacao': typeof AuthenticatedIluminacaoRoute
  '/_authenticated/publico': typeof AuthenticatedPublicoRoute
  '/_authenticated/som': typeof AuthenticatedSomRoute
  '/motorista-print/$slug': typeof MotoristaPrintSlugRoute
  '/rb/$slug': typeof RbSlugRoute
  '/turne-completa/$slug': typeof TurneCompletaSlugRoute
  '/turne/$slug': typeof TurneSlugRoute
  '/_authenticated/print/$slug': typeof AuthenticatedPrintSlugRoute
  '/_authenticated/roadbook/$id': typeof AuthenticatedRoadbookIdRoute
  '/_authenticated/roadbook/new': typeof AuthenticatedRoadbookNewRoute
  '/_authenticated/tour/$id': typeof AuthenticatedTourIdRoute
  '/_authenticated/tour/new': typeof AuthenticatedTourNewRoute
  '/_authenticated/versao-motorista/$slug': typeof AuthenticatedVersaoMotoristaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastros'
    | '/dashboard'
    | '/eventos'
    | '/financeiro'
    | '/iluminacao'
    | '/publico'
    | '/som'
    | '/motorista-print/$slug'
    | '/rb/$slug'
    | '/turne-completa/$slug'
    | '/turne/$slug'
    | '/print/$slug'
    | '/roadbook/$id'
    | '/roadbook/new'
    | '/tour/$id'
    | '/tour/new'
    | '/versao-motorista/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastros'
    | '/dashboard'
    | '/eventos'
    | '/financeiro'
    | '/iluminacao'
    | '/publico'
    | '/som'
    | '/motorista-print/$slug'
    | '/rb/$slug'
    | '/turne-completa/$slug'
    | '/turne/$slug'
    | '/print/$slug'
    | '/roadbook/$id'
    | '/roadbook/new'
    | '/tour/$id'
    | '/tour/new'
    | '/versao-motorista/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cadastros'
    | '/_authenticated/dashboard'
    | '/_authenticated/eventos'
    | '/_authenticated/financeiro'
    | '/_authenticated/iluminacao'
    | '/_authenticated/publico'
    | '/_authenticated/som'
    | '/motorista-print/$slug'
    | '/rb/$slug'
    | '/turne-completa/$slug'
    | '/turne/$slug'
    | '/_authenticated/print/$slug'
    | '/_authenticated/roadbook/$id'
    | '/_authenticated/roadbook/new'
    | '/_authenticated/tour/$id'
    | '/_authenticated/tour/new'
    | '/_authenticated/versao-motorista/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MotoristaPrintSlugRoute: typeof MotoristaPrintSlugRoute
  RbSlugRoute: typeof RbSlugRoute
  TurneCompletaSlugRoute: typeof TurneCompletaSlugRoute
  TurneSlugRoute: typeof TurneSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turne/$slug': {
      id: '/turne/$slug'
      path: '/turne/$slug'
      fullPath: '/turne/$slug'
      preLoaderRoute: typeof TurneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turne-completa/$slug': {
      id: '/turne-completa/$slug'
      path: '/turne-completa/$slug'
      fullPath: '/turne-completa/$slug'
      preLoaderRoute: typeof TurneCompletaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rb/$slug': {
      id: '/rb/$slug'
      path: '/rb/$slug'
      fullPath: '/rb/$slug'
      preLoaderRoute: typeof RbSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista-print/$slug': {
      id: '/motorista-print/$slug'
      path: '/motorista-print/$slug'
      fullPath: '/motorista-print/$slug'
      preLoaderRoute: typeof MotoristaPrintSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/som': {
      id: '/_authenticated/som'
      path: '/som'
      fullPath: '/som'
      preLoaderRoute: typeof AuthenticatedSomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publico': {
      id: '/_authenticated/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof AuthenticatedPublicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/iluminacao': {
      id: '/_authenticated/iluminacao'
      path: '/iluminacao'
      fullPath: '/iluminacao'
      preLoaderRoute: typeof AuthenticatedIluminacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/versao-motorista/$slug': {
      id: '/_authenticated/versao-motorista/$slug'
      path: '/versao-motorista/$slug'
      fullPath: '/versao-motorista/$slug'
      preLoaderRoute: typeof AuthenticatedVersaoMotoristaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour/new': {
      id: '/_authenticated/tour/new'
      path: '/tour/new'
      fullPath: '/tour/new'
      preLoaderRoute: typeof AuthenticatedTourNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tour/$id': {
      id: '/_authenticated/tour/$id'
      path: '/tour/$id'
      fullPath: '/tour/$id'
      preLoaderRoute: typeof AuthenticatedTourIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadbook/new': {
      id: '/_authenticated/roadbook/new'
      path: '/roadbook/new'
      fullPath: '/roadbook/new'
      preLoaderRoute: typeof AuthenticatedRoadbookNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadbook/$id': {
      id: '/_authenticated/roadbook/$id'
      path: '/roadbook/$id'
      fullPath: '/roadbook/$id'
      preLoaderRoute: typeof AuthenticatedRoadbookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/$slug': {
      id: '/_authenticated/print/$slug'
      path: '/print/$slug'
      fullPath: '/print/$slug'
      preLoaderRoute: typeof AuthenticatedPrintSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIluminacaoRoute: typeof AuthenticatedIluminacaoRoute
  AuthenticatedPublicoRoute: typeof AuthenticatedPublicoRoute
  AuthenticatedSomRoute: typeof AuthenticatedSomRoute
  AuthenticatedPrintSlugRoute: typeof AuthenticatedPrintSlugRoute
  AuthenticatedRoadbookIdRoute: typeof AuthenticatedRoadbookIdRoute
  AuthenticatedRoadbookNewRoute: typeof AuthenticatedRoadbookNewRoute
  AuthenticatedTourIdRoute: typeof AuthenticatedTourIdRoute
  AuthenticatedTourNewRoute: typeof AuthenticatedTourNewRoute
  AuthenticatedVersaoMotoristaSlugRoute: typeof AuthenticatedVersaoMotoristaSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIluminacaoRoute: AuthenticatedIluminacaoRoute,
  AuthenticatedPublicoRoute: AuthenticatedPublicoRoute,
  AuthenticatedSomRoute: AuthenticatedSomRoute,
  AuthenticatedPrintSlugRoute: AuthenticatedPrintSlugRoute,
  AuthenticatedRoadbookIdRoute: AuthenticatedRoadbookIdRoute,
  AuthenticatedRoadbookNewRoute: AuthenticatedRoadbookNewRoute,
  AuthenticatedTourIdRoute: AuthenticatedTourIdRoute,
  AuthenticatedTourNewRoute: AuthenticatedTourNewRoute,
  AuthenticatedVersaoMotoristaSlugRoute: AuthenticatedVersaoMotoristaSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MotoristaPrintSlugRoute: MotoristaPrintSlugRoute,
  RbSlugRoute: RbSlugRoute,
  TurneCompletaSlugRoute: TurneCompletaSlugRoute,
  TurneSlugRoute: TurneSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
